# Ticker map built for the momentum board. ~500 NSE stocks + 38 ETFs.
# Names tagged  # VERIFY  are ones to confirm (renames / less-common scrips).
# 'Dummy Valor Estate Ltd.' was excluded — it is a non-tradeable dummy scrip.

INDICES = {
    'Nasdaq 100': {"yahoo": "MON100.NS", "fyers": "NSE:MON100-EQ"},
    'Silver Bees': {"yahoo": "SILVERBEES.NS", "fyers": "NSE:SILVERBEES-EQ"},
    'S&P 500 Top 50 Total Return Index': {"yahoo": "MASPTOP50.NS", "fyers": "NSE:MASPTOP50-EQ"},
    'NYSE FANG+ Total Return Index': {"yahoo": "MAFANG.NS", "fyers": "NSE:MAFANG-EQ"},
    'Gold Bees': {"yahoo": "GOLDBEES.NS", "fyers": "NSE:GOLDBEES-EQ"},
    'Nifty Metal Index': {"yahoo": "METALIETF.NS", "fyers": "NSE:METALIETF-EQ"},
    'Nifty Capital Market Total Return Index': {"yahoo": "MOCAPITAL.NS", "fyers": "NSE:MOCAPITAL-EQ"},
    'Nifty Pharma Tri': {"yahoo": "PHARMABEES.NS", "fyers": "NSE:PHARMABEES-EQ"},
    'Defence': {"yahoo": "MODEFENCE.NS", "fyers": "NSE:MODEFENCE-EQ"},
    'Central Public Sector Enterprises': {"yahoo": "CPSEETF.NS", "fyers": "NSE:CPSEETF-EQ"},
    'Hang Seng Index': {"yahoo": "HNGSNGBEES.NS", "fyers": "NSE:HNGSNGBEES-EQ"},
    'Nifty Midcap 100': {"yahoo": "MOM100.NS", "fyers": "NSE:MOM100-EQ"},
    'Midcap 150': {"yahoo": "MIDCAPETF.NS", "fyers": "NSE:MIDCAPETF-EQ"},
    'Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF': {"yahoo": "SMALLCAP.NS", "fyers": "NSE:SMALLCAP-EQ"},
    'NIFTY Alpha 50 Index': {"yahoo": "ALPHA.NS", "fyers": "NSE:ALPHA-EQ"},
    'Liquid Fund': {"yahoo": "LIQUIDCASE.NS", "fyers": "NSE:LIQUIDCASE-EQ"},
    'Nifty Smallcap 250': {"yahoo": "HDFCSML250.NS", "fyers": "NSE:HDFCSML250-EQ"},
    'Mirae Asset Nifty 200 Alpha 30 ETF': {"yahoo": "ALPHAETF.NS", "fyers": "NSE:ALPHAETF-EQ"},
    'Nifty Next 50': {"yahoo": "JUNIORBEES.NS", "fyers": "NSE:JUNIORBEES-EQ"},
    'Nifty Infrastructure': {"yahoo": "INFRAIETF.NS", "fyers": "NSE:INFRAIETF-EQ"},
    'ICICI Prudential Nifty Financial Services Ex-Bank ETF': {"yahoo": "FINIETF.NS", "fyers": "NSE:FINIETF-EQ"},
    'Nifty BHARAT Bond': {"yahoo": "EBBETF0430.NS", "fyers": "NSE:EBBETF0430-EQ"},
    'Nifty 500 Momentum 50 Total Return Index': {"yahoo": "MOMENTUM50.NS", "fyers": "NSE:MOMENTUM50-EQ"},
    'Nifty EV and New Age Automotive Total Return Index': {"yahoo": "EVINDIA.NS", "fyers": "NSE:EVINDIA-EQ"},
    'Nifty Auto Index': {"yahoo": "AUTOIETF.NS", "fyers": "NSE:AUTOIETF-EQ"},
    'ICICI Prudential Nifty 200 Momentum 30 ETF': {"yahoo": "MOM30IETF.NS", "fyers": "NSE:MOM30IETF-EQ"},
    'Nifty 100 Low Volatility 30 Index': {"yahoo": "LOWVOLIETF.NS", "fyers": "NSE:LOWVOLIETF-EQ"},
    'Hang Seng TECH Total Return Index': {"yahoo": "MAHKTECH.NS", "fyers": "NSE:MAHKTECH-EQ"},
    'Nifty FMCG Index': {"yahoo": "FMCGIETF.NS", "fyers": "NSE:FMCGIETF-EQ"},
    'Nifty 50 Bees': {"yahoo": "NIFTYBEES.NS", "fyers": "NSE:NIFTYBEES-EQ"},
    'Nifty Private Bank Index': {"yahoo": "PVTBANIETF.NS", "fyers": "NSE:PVTBANIETF-EQ"},
    'Nifty Financial Services Index': {"yahoo": "BFSI.NS", "fyers": "NSE:BFSI-EQ"},
    'Bank Bees': {"yahoo": "BANKBEES.NS", "fyers": "NSE:BANKBEES-EQ"},
    'Nifty PSU Bank': {"yahoo": "PSUBNKBEES.NS", "fyers": "NSE:PSUBNKBEES-EQ"},
    'Nifty India Railways PSU Index': {"yahoo": "GROWWRAIL.NS", "fyers": "NSE:GROWWRAIL-EQ"},
    'Nifty Top 10 Equal Weight Index': {"yahoo": "TOP10ADD.NS", "fyers": "NSE:TOP10ADD-EQ"},
    'Motilal Oswal Nifty Realty ETF': {"yahoo": "MOREALTY.NS", "fyers": "NSE:MOREALTY-EQ"},
    'IT Bees': {"yahoo": "ITBEES.NS", "fyers": "NSE:ITBEES-EQ"},
}

STOCKS = {
    'HFCL Ltd.': {"yahoo": "HFCL.NS", "fyers": "NSE:HFCL-EQ"},
    'Hitachi Energy India Ltd.': {"yahoo": "POWERINDIA.NS", "fyers": "NSE:POWERINDIA-EQ"},
    'GE Vernova T&D India Ltd.': {"yahoo": "GVT&D.NS", "fyers": "NSE:GVT&D-EQ"},
    'Schneider Electric Infrastructure Ltd.': {"yahoo": "SCHNEIDER.NS", "fyers": "NSE:SCHNEIDER-EQ"},
    'Adani Power Ltd.': {"yahoo": "ADANIPOWER.NS", "fyers": "NSE:ADANIPOWER-EQ"},
    'Kirloskar Oil Eng Ltd.': {"yahoo": "KIRLOSENG.NS", "fyers": "NSE:KIRLOSENG-EQ"},
    'Adani Green Energy Ltd.': {"yahoo": "ADANIGREEN.NS", "fyers": "NSE:ADANIGREEN-EQ"},
    'Thermax Ltd.': {"yahoo": "THERMAX.NS", "fyers": "NSE:THERMAX-EQ"},
    'Adani Energy Solutions Ltd.': {"yahoo": "ADANIENSOL.NS", "fyers": "NSE:ADANIENSOL-EQ"},
    'Welspun Corp Ltd.': {"yahoo": "WELCORP.NS", "fyers": "NSE:WELCORP-EQ"},
    'Bharat Heavy Electricals Ltd.': {"yahoo": "BHEL.NS", "fyers": "NSE:BHEL-EQ"},
    'Vodafone Idea Ltd.': {"yahoo": "IDEA.NS", "fyers": "NSE:IDEA-EQ"},
    'Apar Industries Ltd.': {"yahoo": "APARINDS.NS", "fyers": "NSE:APARINDS-EQ"},
    'Wockhardt Ltd.': {"yahoo": "WOCKPHARMA.NS", "fyers": "NSE:WOCKPHARMA-EQ"},
    'Data Patterns (India) Ltd.': {"yahoo": "DATAPATTNS.NS", "fyers": "NSE:DATAPATTNS-EQ"},
    'Syrma SGS Technology Ltd.': {"yahoo": "SYRMA.NS", "fyers": "NSE:SYRMA-EQ"},
    'R R Kabel Ltd.': {"yahoo": "RRKABEL.NS", "fyers": "NSE:RRKABEL-EQ"},
    'Netweb Technologies India Ltd.': {"yahoo": "NETWEB.NS", "fyers": "NSE:NETWEB-EQ"},
    'Triveni Turbine Ltd.': {"yahoo": "TRITURBINE.NS", "fyers": "NSE:TRITURBINE-EQ"},
    'Laurus Labs Ltd.': {"yahoo": "LAURUSLABS.NS", "fyers": "NSE:LAURUSLABS-EQ"},
    'BSE Ltd.': {"yahoo": "BSE.NS", "fyers": "NSE:BSE-EQ"},
    'Finolex Cables Ltd.': {"yahoo": "FINCABLES.NS", "fyers": "NSE:FINCABLES-EQ"},
    'Honasa Consumer Ltd.': {"yahoo": "HONASA.NS", "fyers": "NSE:HONASA-EQ"},
    'CG Power and Industrial Solutions Ltd.': {"yahoo": "CGPOWER.NS", "fyers": "NSE:CGPOWER-EQ"},
    'Adani Total Gas Ltd.': {"yahoo": "ATGL.NS", "fyers": "NSE:ATGL-EQ"},
    'Cummins India Ltd.': {"yahoo": "CUMMINSIND.NS", "fyers": "NSE:CUMMINSIND-EQ"},
    'Adani Enterprises Ltd.': {"yahoo": "ADANIENT.NS", "fyers": "NSE:ADANIENT-EQ"},
    'Gland Pharma Ltd.': {"yahoo": "GLAND.NS", "fyers": "NSE:GLAND-EQ"},
    'Polycab India Ltd.': {"yahoo": "POLYCAB.NS", "fyers": "NSE:POLYCAB-EQ"},
    'Lloyds Metals And Energy Ltd.': {"yahoo": "LLOYDSME.NS", "fyers": "NSE:LLOYDSME-EQ"},
    'Solar Industries India Ltd.': {"yahoo": "SOLARINDS.NS", "fyers": "NSE:SOLARINDS-EQ"},
    'Steel Authority of India Ltd.': {"yahoo": "SAIL.NS", "fyers": "NSE:SAIL-EQ"},
    'NLC India Ltd.': {"yahoo": "NLCINDIA.NS", "fyers": "NSE:NLCINDIA-EQ"},
    'National Aluminium Co. Ltd.': {"yahoo": "NATIONALUM.NS", "fyers": "NSE:NATIONALUM-EQ"},
    'Multi Commodity Exchange of India Ltd.': {"yahoo": "MCX.NS", "fyers": "NSE:MCX-EQ"},
    'Craftsman Automation Ltd.': {"yahoo": "CRAFTSMAN.NS", "fyers": "NSE:CRAFTSMAN-EQ"},
    'Granules India Ltd.': {"yahoo": "GRANULES.NS", "fyers": "NSE:GRANULES-EQ"},
    'Sai Life Sciences Ltd.': {"yahoo": "SAILIFE.NS", "fyers": "NSE:SAILIFE-EQ"},
    'Tejas Networks Ltd.': {"yahoo": "TEJASNET.NS", "fyers": "NSE:TEJASNET-EQ"},
    'ABB India Ltd.': {"yahoo": "ABB.NS", "fyers": "NSE:ABB-EQ"},
    'ACME Solar Holdings Ltd.': {"yahoo": "ACMESOLAR.NS", "fyers": "NSE:ACMESOLAR-EQ"},
    'Jaiprakash Power Ventures Ltd.': {"yahoo": "JPPOWER.NS", "fyers": "NSE:JPPOWER-EQ"},
    'KEI Industries Ltd.': {"yahoo": "KEI.NS", "fyers": "NSE:KEI-EQ"},
    'Bandhan Bank Ltd.': {"yahoo": "BANDHANBNK.NS", "fyers": "NSE:BANDHANBNK-EQ"},
    'Sammaan Capital Ltd.': {"yahoo": "SAMMAANCAP.NS", "fyers": "NSE:SAMMAANCAP-EQ"},
    'Hindalco Industries Ltd.': {"yahoo": "HINDALCO.NS", "fyers": "NSE:HINDALCO-EQ"},
    'Jammu & Kashmir Bank Ltd.': {"yahoo": "J&KBANK.NS", "fyers": "NSE:J&KBANK-EQ"},
    'Shipping Corporation of India Ltd.': {"yahoo": "SCI.NS", "fyers": "NSE:SCI-EQ"},
    'NATCO Pharma Ltd.': {"yahoo": "NATCOPHARM.NS", "fyers": "NSE:NATCOPHARM-EQ"},
    'Nippon Life India Asset Management Ltd.': {"yahoo": "NAM-INDIA.NS", "fyers": "NSE:NAM-INDIA-EQ"},
    'Bharat Forge Ltd.': {"yahoo": "BHARATFORG.NS", "fyers": "NSE:BHARATFORG-EQ"},
    'Vijaya Diagnostic Centre Ltd.': {"yahoo": "VIJAYA.NS", "fyers": "NSE:VIJAYA-EQ"},
    'Hindustan Copper Ltd.': {"yahoo": "HINDCOPPER.NS", "fyers": "NSE:HINDCOPPER-EQ"},
    'Samvardhana Motherson International Ltd.': {"yahoo": "MOTHERSON.NS", "fyers": "NSE:MOTHERSON-EQ"},
    'INOX India Ltd.': {"yahoo": "INOXINDIA.NS", "fyers": "NSE:INOXINDIA-EQ"},
    'Navin Fluorine International Ltd.': {"yahoo": "NAVINFLUOR.NS", "fyers": "NSE:NAVINFLUOR-EQ"},
    'Vardhman Textiles Ltd.': {"yahoo": "VTL.NS", "fyers": "NSE:VTL-EQ"},
    'Raymond Ltd.': {"yahoo": "RAYMOND.NS", "fyers": "NSE:RAYMOND-EQ"},
    'Adani Ports and Special Economic Zone Ltd.': {"yahoo": "ADANIPORTS.NS", "fyers": "NSE:ADANIPORTS-EQ"},
    'Jindal Saw Ltd.': {"yahoo": "JINDALSAW.NS", "fyers": "NSE:JINDALSAW-EQ"},
    'IFCI Ltd.': {"yahoo": "IFCI.NS", "fyers": "NSE:IFCI-EQ"},
    'Tube Investments of India Ltd.': {"yahoo": "TIINDIA.NS", "fyers": "NSE:TIINDIA-EQ"},
    'Aditya Birla Sun Life AMC Ltd.': {"yahoo": "ABSLAMC.NS", "fyers": "NSE:ABSLAMC-EQ"},
    'Angel One Ltd.': {"yahoo": "ANGELONE.NS", "fyers": "NSE:ANGELONE-EQ"},
    'Usha Martin Ltd.': {"yahoo": "USHAMART.NS", "fyers": "NSE:USHAMART-EQ"},
    'Graphite India Ltd.': {"yahoo": "GRAPHITE.NS", "fyers": "NSE:GRAPHITE-EQ"},
    'Elgi Equipments Ltd.': {"yahoo": "ELGIEQUIP.NS", "fyers": "NSE:ELGIEQUIP-EQ"},
    'Zydus Lifesciences Ltd.': {"yahoo": "ZYDUSLIFE.NS", "fyers": "NSE:ZYDUSLIFE-EQ"},
    'Krishna Institute of Medical Sciences Ltd.': {"yahoo": "KIMS.NS", "fyers": "NSE:KIMS-EQ"},
    'Bank of Maharashtra': {"yahoo": "MAHABANK.NS", "fyers": "NSE:MAHABANK-EQ"},
    'Carborundum Universal Ltd.': {"yahoo": "CARBORUNIV.NS", "fyers": "NSE:CARBORUNIV-EQ"},
    'Himadri Speciality Chemical Ltd.': {"yahoo": "HIMADRI.NS", "fyers": "NSE:HIMADRI-EQ"},  # VERIFY
    'Gujarat Mineral Development Corporation Ltd.': {"yahoo": "GMDCLTD.NS", "fyers": "NSE:GMDCLTD-EQ"},
    'AIA Engineering Ltd.': {"yahoo": "AIAENG.NS", "fyers": "NSE:AIAENG-EQ"},
    'Premier Energies Ltd.': {"yahoo": "PREMIERENE.NS", "fyers": "NSE:PREMIERENE-EQ"},
    'Aster DM Healthcare Ltd.': {"yahoo": "ASTERDM.NS", "fyers": "NSE:ASTERDM-EQ"},
    'JSW Energy Ltd.': {"yahoo": "JSWENERGY.NS", "fyers": "NSE:JSWENERGY-EQ"},
    'Biocon Ltd.': {"yahoo": "BIOCON.NS", "fyers": "NSE:BIOCON-EQ"},
    'Tata Communications Ltd.': {"yahoo": "TATACOMM.NS", "fyers": "NSE:TATACOMM-EQ"},
    'Sona BLW Precision Forgings Ltd.': {"yahoo": "SONACOMS.NS", "fyers": "NSE:SONACOMS-EQ"},
    'Ola Electric Mobility Ltd.': {"yahoo": "OLAELEC.NS", "fyers": "NSE:OLAELEC-EQ"},
    'Metropolis Healthcare Ltd.': {"yahoo": "METROPOLIS.NS", "fyers": "NSE:METROPOLIS-EQ"},
    'Aarti Industries Ltd.': {"yahoo": "AARTIIND.NS", "fyers": "NSE:AARTIIND-EQ"},
    'Neuland Laboratories Ltd.': {"yahoo": "NEULANDLAB.NS", "fyers": "NSE:NEULANDLAB-EQ"},
    'Siemens Ltd.': {"yahoo": "SIEMENS.NS", "fyers": "NSE:SIEMENS-EQ"},
    'Saregama India Ltd': {"yahoo": "SAREGAMA.NS", "fyers": "NSE:SAREGAMA-EQ"},
    'Shyam Metalics and Energy Ltd.': {"yahoo": "SHYAMMETL.NS", "fyers": "NSE:SHYAMMETL-EQ"},
    'Oracle Financial Services Software Ltd.': {"yahoo": "OFSS.NS", "fyers": "NSE:OFSS-EQ"},
    'Elecon Engineering Co. Ltd.': {"yahoo": "ELECON.NS", "fyers": "NSE:ELECON-EQ"},
    'Godrej Industries Ltd.': {"yahoo": "GODREJIND.NS", "fyers": "NSE:GODREJIND-EQ"},
    'Linde India Ltd.': {"yahoo": "LINDEINDIA.NS", "fyers": "NSE:LINDEINDIA-EQ"},
    'Anand Rathi Wealth Ltd.': {"yahoo": "ANANDRATHI.NS", "fyers": "NSE:ANANDRATHI-EQ"},
    'Aurobindo Pharma Ltd.': {"yahoo": "AUROPHARMA.NS", "fyers": "NSE:AUROPHARMA-EQ"},
    'Alivus Life Sciences Ltd.': {"yahoo": "ALIVUS.NS", "fyers": "NSE:ALIVUS-EQ"},
    'Great Eastern Shipping Co. Ltd.': {"yahoo": "GESHIP.NS", "fyers": "NSE:GESHIP-EQ"},
    'Minda Corporation Ltd.': {"yahoo": "MINDACORP.NS", "fyers": "NSE:MINDACORP-EQ"},
    'RBL Bank Ltd.': {"yahoo": "RBLBANK.NS", "fyers": "NSE:RBLBANK-EQ"},
    'Nuvama Wealth Management Ltd.': {"yahoo": "NUVAMA.NS", "fyers": "NSE:NUVAMA-EQ"},
    'Caplin Point Laboratories Ltd.': {"yahoo": "CAPLIPOINT.NS", "fyers": "NSE:CAPLIPOINT-EQ"},
    'Deepak Fertilisers & Petrochemicals Corp. Ltd.': {"yahoo": "DEEPAKFERT.NS", "fyers": "NSE:DEEPAKFERT-EQ"},
    'Sumitomo Chemical India Ltd.': {"yahoo": "SUMICHEM.NS", "fyers": "NSE:SUMICHEM-EQ"},
    'Transformers And Rectifiers (India) Ltd.': {"yahoo": "TARIL.NS", "fyers": "NSE:TARIL-EQ"},  # VERIFY
    'Apollo Hospitals Enterprise Ltd.': {"yahoo": "APOLLOHOSP.NS", "fyers": "NSE:APOLLOHOSP-EQ"},
    'Grasim Industries Ltd.': {"yahoo": "GRASIM.NS", "fyers": "NSE:GRASIM-EQ"},
    'Amber Enterprises India Ltd.': {"yahoo": "AMBER.NS", "fyers": "NSE:AMBER-EQ"},
    'Manappuram Finance Ltd.': {"yahoo": "MANAPPURAM.NS", "fyers": "NSE:MANAPPURAM-EQ"},
    'Glenmark Pharmaceuticals Ltd.': {"yahoo": "GLENMARK.NS", "fyers": "NSE:GLENMARK-EQ"},
    'Bajaj Auto Ltd.': {"yahoo": "BAJAJ-AUTO.NS", "fyers": "NSE:BAJAJ-AUTO-EQ"},
    'J.B. Chemicals & Pharmaceuticals Ltd.': {"yahoo": "JBCHEPHARM.NS", "fyers": "NSE:JBCHEPHARM-EQ"},
    'Engineers India Ltd.': {"yahoo": "ENGINERSIN.NS", "fyers": "NSE:ENGINERSIN-EQ"},
    'Chennai Petroleum Corporation Ltd.': {"yahoo": "CHENNPETRO.NS", "fyers": "NSE:CHENNPETRO-EQ"},
    'Endurance Technologies Ltd.': {"yahoo": "ENDURANCE.NS", "fyers": "NSE:ENDURANCE-EQ"},
    'Radico Khaitan Ltd': {"yahoo": "RADICO.NS", "fyers": "NSE:RADICO-EQ"},
    'Torrent Pharmaceuticals Ltd.': {"yahoo": "TORNTPHARM.NS", "fyers": "NSE:TORNTPHARM-EQ"},
    'Dr. Lal Path Labs Ltd.': {"yahoo": "LALPATHLAB.NS", "fyers": "NSE:LALPATHLAB-EQ"},
    'Tata Technologies Ltd.': {"yahoo": "TATATECH.NS", "fyers": "NSE:TATATECH-EQ"},
    'Zen Technologies Ltd.': {"yahoo": "ZENTEC.NS", "fyers": "NSE:ZENTEC-EQ"},
    'Tata Steel Ltd.': {"yahoo": "TATASTEEL.NS", "fyers": "NSE:TATASTEEL-EQ"},
    'Yes Bank Ltd.': {"yahoo": "YESBANK.NS", "fyers": "NSE:YESBANK-EQ"},
    'Marico Ltd.': {"yahoo": "MARICO.NS", "fyers": "NSE:MARICO-EQ"},
    'International Gemmological Institute (India) Ltd.': {"yahoo": "IGIL.NS", "fyers": "NSE:IGIL-EQ"},
    'Timken India Ltd.': {"yahoo": "TIMKEN.NS", "fyers": "NSE:TIMKEN-EQ"},
    'Crompton Greaves Consumer Electricals Ltd.': {"yahoo": "CROMPTON.NS", "fyers": "NSE:CROMPTON-EQ"},
    'NMDC Ltd.': {"yahoo": "NMDC.NS", "fyers": "NSE:NMDC-EQ"},
    'Motilal Oswal Financial Services Ltd.': {"yahoo": "MOTILALOFS.NS", "fyers": "NSE:MOTILALOFS-EQ"},
    'Emcure Pharmaceuticals Ltd.': {"yahoo": "EMCURE.NS", "fyers": "NSE:EMCURE-EQ"},
    'NMDC Steel Ltd.': {"yahoo": "NSLNISP.NS", "fyers": "NSE:NSLNISP-EQ"},  # VERIFY
    'PNB Housing Finance Ltd.': {"yahoo": "PNBHOUSING.NS", "fyers": "NSE:PNBHOUSING-EQ"},
    'Balrampur Chini Mills Ltd.': {"yahoo": "BALRAMCHIN.NS", "fyers": "NSE:BALRAMCHIN-EQ"},
    'Capri Global Capital Ltd.': {"yahoo": "CGCL.NS", "fyers": "NSE:CGCL-EQ"},
    'Akums Drugs and Pharmaceuticals Ltd.': {"yahoo": "AKUMS.NS", "fyers": "NSE:AKUMS-EQ"},
    'Godawari Power & Ispat Ltd.': {"yahoo": "GPIL.NS", "fyers": "NSE:GPIL-EQ"},
    'CESC Ltd.': {"yahoo": "CESC.NS", "fyers": "NSE:CESC-EQ"},
    'Karur Vysya Bank Ltd.': {"yahoo": "KARURVYSYA.NS", "fyers": "NSE:KARURVYSYA-EQ"},
    'Jindal Steel & Power Ltd.': {"yahoo": "JINDALSTEL.NS", "fyers": "NSE:JINDALSTEL-EQ"},
    'Honeywell Automation India Ltd.': {"yahoo": "HONAUT.NS", "fyers": "NSE:HONAUT-EQ"},
    'NTPC Ltd.': {"yahoo": "NTPC.NS", "fyers": "NSE:NTPC-EQ"},
    'Varun Beverages Ltd.': {"yahoo": "VBL.NS", "fyers": "NSE:VBL-EQ"},
    'HBL Engineering Ltd.': {"yahoo": "HBLENGINE.NS", "fyers": "NSE:HBLENGINE-EQ"},  # VERIFY
    'Star Health and Allied Insurance Company Ltd.': {"yahoo": "STARHEALTH.NS", "fyers": "NSE:STARHEALTH-EQ"},
    'Ajanta Pharmaceuticals Ltd.': {"yahoo": "AJANTPHARM.NS", "fyers": "NSE:AJANTPHARM-EQ"},
    'Atul Ltd.': {"yahoo": "ATUL.NS", "fyers": "NSE:ATUL-EQ"},
    'Exide Industries Ltd.': {"yahoo": "EXIDEIND.NS", "fyers": "NSE:EXIDEIND-EQ"},
    'GMR Airports Ltd.': {"yahoo": "GMRAIRPORT.NS", "fyers": "NSE:GMRAIRPORT-EQ"},
    'Delhivery Ltd.': {"yahoo": "DELHIVERY.NS", "fyers": "NSE:DELHIVERY-EQ"},
    'JSW Steel Ltd.': {"yahoo": "JSWSTEEL.NS", "fyers": "NSE:JSWSTEEL-EQ"},
    'Gujarat Fluorochemicals Ltd.': {"yahoo": "FLUOROCHEM.NS", "fyers": "NSE:FLUOROCHEM-EQ"},
    'Mankind Pharma Ltd.': {"yahoo": "MANKIND.NS", "fyers": "NSE:MANKIND-EQ"},
    'Aditya Birla Capital Ltd.': {"yahoo": "ABCAPITAL.NS", "fyers": "NSE:ABCAPITAL-EQ"},
    'Kalpataru Projects International Ltd.': {"yahoo": "KPIL.NS", "fyers": "NSE:KPIL-EQ"},
    'Hindustan Zinc Ltd.': {"yahoo": "HINDZINC.NS", "fyers": "NSE:HINDZINC-EQ"},
    'Niva Bupa Health Insurance Company Ltd.': {"yahoo": "NIVABUPA.NS", "fyers": "NSE:NIVABUPA-EQ"},
    'Federal Bank Ltd.': {"yahoo": "FEDERALBNK.NS", "fyers": "NSE:FEDERALBNK-EQ"},
    'Power Finance Corporation Ltd.': {"yahoo": "PFC.NS", "fyers": "NSE:PFC-EQ"},
    'Suzlon Energy Ltd.': {"yahoo": "SUZLON.NS", "fyers": "NSE:SUZLON-EQ"},
    'Indus Towers Ltd.': {"yahoo": "INDUSTOWER.NS", "fyers": "NSE:INDUSTOWER-EQ"},
    'Astral Ltd.': {"yahoo": "ASTRAL.NS", "fyers": "NSE:ASTRAL-EQ"},
    'Welspun Living Ltd.': {"yahoo": "WELSPUNLIV.NS", "fyers": "NSE:WELSPUNLIV-EQ"},
    'Coal India Ltd.': {"yahoo": "COALINDIA.NS", "fyers": "NSE:COALINDIA-EQ"},
    'Cera Sanitaryware Ltd': {"yahoo": "CERA.NS", "fyers": "NSE:CERA-EQ"},
    'Fortis Healthcare Ltd.': {"yahoo": "FORTIS.NS", "fyers": "NSE:FORTIS-EQ"},
    'JBM Auto Ltd.': {"yahoo": "JBMA.NS", "fyers": "NSE:JBMA-EQ"},
    'Maharashtra Seamless Ltd.': {"yahoo": "MAHSEAMLES.NS", "fyers": "NSE:MAHSEAMLES-EQ"},
    'Rainbow Childrens Medicare Ltd.': {"yahoo": "RAINBOW.NS", "fyers": "NSE:RAINBOW-EQ"},
    'CCL Products (I) Ltd.': {"yahoo": "CCL.NS", "fyers": "NSE:CCL-EQ"},
    'Tata Power Co. Ltd.': {"yahoo": "TATAPOWER.NS", "fyers": "NSE:TATAPOWER-EQ"},
    'Global Health Ltd.': {"yahoo": "MEDANTA.NS", "fyers": "NSE:MEDANTA-EQ"},
    'Nestle India Ltd.': {"yahoo": "NESTLEIND.NS", "fyers": "NSE:NESTLEIND-EQ"},
    'Computer Age Management Services Ltd.': {"yahoo": "CAMS.NS", "fyers": "NSE:CAMS-EQ"},
    'Ipca Laboratories Ltd.': {"yahoo": "IPCALAB.NS", "fyers": "NSE:IPCALAB-EQ"},
    'Narayana Hrudayalaya Ltd.': {"yahoo": "NH.NS", "fyers": "NSE:NH-EQ"},
    'Finolex Industries Ltd.': {"yahoo": "FINPIPE.NS", "fyers": "NSE:FINPIPE-EQ"},
    'Titagarh Rail Systems Ltd.': {"yahoo": "TITAGARH.NS", "fyers": "NSE:TITAGARH-EQ"},
    'FSN E-Commerce Ventures Ltd.': {"yahoo": "NYKAA.NS", "fyers": "NSE:NYKAA-EQ"},
    'Valor Estate Ltd.': {"yahoo": "DBREALTY.NS", "fyers": "NSE:DBREALTY-EQ"},
    'Oil India Ltd.': {"yahoo": "OIL.NS", "fyers": "NSE:OIL-EQ"},
    'NTPC Green Energy Ltd.': {"yahoo": "NTPCGREEN.NS", "fyers": "NSE:NTPCGREEN-EQ"},
    'Sun Pharmaceutical Industries Ltd.': {"yahoo": "SUNPHARMA.NS", "fyers": "NSE:SUNPHARMA-EQ"},
    'Eicher Motors Ltd.': {"yahoo": "EICHERMOT.NS", "fyers": "NSE:EICHERMOT-EQ"},
    'Nava Ltd.': {"yahoo": "NAVA.NS", "fyers": "NSE:NAVA-EQ"},
    "Divi's Laboratories Ltd.": {"yahoo": "DIVISLAB.NS", "fyers": "NSE:DIVISLAB-EQ"},
    'Page Industries Ltd.': {"yahoo": "PAGEIND.NS", "fyers": "NSE:PAGEIND-EQ"},
    'Gujarat Narmada Valley Fertilizers and Chemicals Ltd.': {"yahoo": "GNFC.NS", "fyers": "NSE:GNFC-EQ"},
    'Olectra Greentech Ltd.': {"yahoo": "OLECTRA.NS", "fyers": "NSE:OLECTRA-EQ"},
    'Piramal Pharma Ltd.': {"yahoo": "PPLPHARMA.NS", "fyers": "NSE:PPLPHARMA-EQ"},
    'Shriram Finance Ltd.': {"yahoo": "SHRIRAMFIN.NS", "fyers": "NSE:SHRIRAMFIN-EQ"},
    'Bosch Ltd.': {"yahoo": "BOSCHLTD.NS", "fyers": "NSE:BOSCHLTD-EQ"},
    'Chambal Fertilizers & Chemicals Ltd.': {"yahoo": "CHAMBLFERT.NS", "fyers": "NSE:CHAMBLFERT-EQ"},
    'Aegis Logistics Ltd.': {"yahoo": "AEGISLOG.NS", "fyers": "NSE:AEGISLOG-EQ"},
    'ZF Commercial Vehicle Control Systems India Ltd.': {"yahoo": "ZFCVINDIA.NS", "fyers": "NSE:ZFCVINDIA-EQ"},
    'Praj Industries Ltd.': {"yahoo": "PRAJIND.NS", "fyers": "NSE:PRAJIND-EQ"},
    'Larsen & Toubro Ltd.': {"yahoo": "LT.NS", "fyers": "NSE:LT-EQ"},
    'Alkyl Amines Chemicals Ltd.': {"yahoo": "ALKYLAMINE.NS", "fyers": "NSE:ALKYLAMINE-EQ"},
    'Oberoi Realty Ltd.': {"yahoo": "OBEROIRLTY.NS", "fyers": "NSE:OBEROIRLTY-EQ"},
    'Lupin Ltd.': {"yahoo": "LUPIN.NS", "fyers": "NSE:LUPIN-EQ"},
    'IndusInd Bank Ltd.': {"yahoo": "INDUSINDBK.NS", "fyers": "NSE:INDUSINDBK-EQ"},
    'AU Small Finance Bank Ltd.': {"yahoo": "AUBANK.NS", "fyers": "NSE:AUBANK-EQ"},
    'Kirloskar Brothers Ltd.': {"yahoo": "KIRLOSBROS.NS", "fyers": "NSE:KIRLOSBROS-EQ"},
    'Max Financial Services Ltd.': {"yahoo": "MFSL.NS", "fyers": "NSE:MFSL-EQ"},
    'HDFC Asset Management Company Ltd.': {"yahoo": "HDFCAMC.NS", "fyers": "NSE:HDFCAMC-EQ"},
    'Union Bank of India': {"yahoo": "UNIONBANK.NS", "fyers": "NSE:UNIONBANK-EQ"},
    'Tata Consumer Products Ltd.': {"yahoo": "TATACONSUM.NS", "fyers": "NSE:TATACONSUM-EQ"},
    'JSW Infrastructure Ltd.': {"yahoo": "JSWINFRA.NS", "fyers": "NSE:JSWINFRA-EQ"},
    'Power Grid Corporation of India Ltd.': {"yahoo": "POWERGRID.NS", "fyers": "NSE:POWERGRID-EQ"},
    'Fertilisers and Chemicals Travancore Ltd.': {"yahoo": "FACT.NS", "fyers": "NSE:FACT-EQ"},
    'Asian Paints Ltd.': {"yahoo": "ASIANPAINT.NS", "fyers": "NSE:ASIANPAINT-EQ"},
    'L&T Finance Ltd.': {"yahoo": "LTF.NS", "fyers": "NSE:LTF-EQ"},
    'Indegene Ltd.': {"yahoo": "INDGN.NS", "fyers": "NSE:INDGN-EQ"},
    'Cipla Ltd.': {"yahoo": "CIPLA.NS", "fyers": "NSE:CIPLA-EQ"},
    'Ramkrishna Forgings Ltd.': {"yahoo": "RKFORGE.NS", "fyers": "NSE:RKFORGE-EQ"},
    'Schaeffler India Ltd.': {"yahoo": "SCHAEFFLER.NS", "fyers": "NSE:SCHAEFFLER-EQ"},
    '360 ONE WAM Ltd.': {"yahoo": "360ONE.NS", "fyers": "NSE:360ONE-EQ"},
    'Trent Ltd.': {"yahoo": "TRENT.NS", "fyers": "NSE:TRENT-EQ"},
    'Axis Bank Ltd.': {"yahoo": "AXISBANK.NS", "fyers": "NSE:AXISBANK-EQ"},
    'MMTC Ltd.': {"yahoo": "MMTC.NS", "fyers": "NSE:MMTC-EQ"},
    'Inventurus Knowledge Solutions Ltd.': {"yahoo": "IKS.NS", "fyers": "NSE:IKS-EQ"},  # VERIFY
    'Waaree Energies Ltd.': {"yahoo": "WAAREEENER.NS", "fyers": "NSE:WAAREEENER-EQ"},
    'Triveni Engineering & Industries Ltd.': {"yahoo": "TRIVENI.NS", "fyers": "NSE:TRIVENI-EQ"},
    'Zee Entertainment Enterprises Ltd.': {"yahoo": "ZEEL.NS", "fyers": "NSE:ZEEL-EQ"},
    'Pidilite Industries Ltd.': {"yahoo": "PIDILITIND.NS", "fyers": "NSE:PIDILITIND-EQ"},
    'K.P.R. Mill Ltd.': {"yahoo": "KPRMILL.NS", "fyers": "NSE:KPRMILL-EQ"},
    'Deepak Nitrite Ltd.': {"yahoo": "DEEPAKNTR.NS", "fyers": "NSE:DEEPAKNTR-EQ"},
    'Godrej Agrovet Ltd.': {"yahoo": "GODREJAGRO.NS", "fyers": "NSE:GODREJAGRO-EQ"},
    'Anant Raj Ltd.': {"yahoo": "ANANTRAJ.NS", "fyers": "NSE:ANANTRAJ-EQ"},
    'NBCC (India) Ltd.': {"yahoo": "NBCC.NS", "fyers": "NSE:NBCC-EQ"},
    'Phoenix Mills Ltd.': {"yahoo": "PHOENIXLTD.NS", "fyers": "NSE:PHOENIXLTD-EQ"},
    'ITI Ltd.': {"yahoo": "ITI.NS", "fyers": "NSE:ITI-EQ"},
    'Berger Paints India Ltd.': {"yahoo": "BERGEPAINT.NS", "fyers": "NSE:BERGEPAINT-EQ"},
    'Amara Raja Energy & Mobility Ltd.': {"yahoo": "ARE&M.NS", "fyers": "NSE:ARE&M-EQ"},
    "Dr. Reddy's Laboratories Ltd.": {"yahoo": "DRREDDY.NS", "fyers": "NSE:DRREDDY-EQ"},
    'BEML Ltd.': {"yahoo": "BEML.NS", "fyers": "NSE:BEML-EQ"},
    'Action Construction Equipment Ltd.': {"yahoo": "ACE.NS", "fyers": "NSE:ACE-EQ"},
    'LT Foods Ltd.': {"yahoo": "LTFOODS.NS", "fyers": "NSE:LTFOODS-EQ"},
    'Titan Company Ltd.': {"yahoo": "TITAN.NS", "fyers": "NSE:TITAN-EQ"},
    'Oil & Natural Gas Corporation Ltd.': {"yahoo": "ONGC.NS", "fyers": "NSE:ONGC-EQ"},
    'H.E.G. Ltd.': {"yahoo": "HEG.NS", "fyers": "NSE:HEG-EQ"},
    'Indian Bank': {"yahoo": "INDIANB.NS", "fyers": "NSE:INDIANB-EQ"},
    'Tata Investment Corporation Ltd.': {"yahoo": "TATAINVEST.NS", "fyers": "NSE:TATAINVEST-EQ"},
    'Godfrey Phillips India Ltd.': {"yahoo": "GODFRYPHLP.NS", "fyers": "NSE:GODFRYPHLP-EQ"},
    'Kajaria Ceramics Ltd.': {"yahoo": "KAJARIACER.NS", "fyers": "NSE:KAJARIACER-EQ"},
    'Jubilant Pharmova Ltd.': {"yahoo": "JUBLPHARMA.NS", "fyers": "NSE:JUBLPHARMA-EQ"},
    'Garden Reach Shipbuilders & Engineers Ltd.': {"yahoo": "GRSE.NS", "fyers": "NSE:GRSE-EQ"},
    'Avenue Supermarts Ltd.': {"yahoo": "DMART.NS", "fyers": "NSE:DMART-EQ"},
    'Supreme Industries Ltd.': {"yahoo": "SUPREMEIND.NS", "fyers": "NSE:SUPREMEIND-EQ"},
    'Alkem Laboratories Ltd.': {"yahoo": "ALKEM.NS", "fyers": "NSE:ALKEM-EQ"},
    'Abbott India Ltd.': {"yahoo": "ABBOTINDIA.NS", "fyers": "NSE:ABBOTINDIA-EQ"},
    'Kansai Nerolac Paints Ltd.': {"yahoo": "KANSAINER.NS", "fyers": "NSE:KANSAINER-EQ"},  # VERIFY
    'The New India Assurance Company Ltd.': {"yahoo": "NIACL.NS", "fyers": "NSE:NIACL-EQ"},
    'SRF Ltd.': {"yahoo": "SRF.NS", "fyers": "NSE:SRF-EQ"},
    'Torrent Power Ltd.': {"yahoo": "TORNTPOWER.NS", "fyers": "NSE:TORNTPOWER-EQ"},
    'Jupiter Wagons Ltd.': {"yahoo": "JWL.NS", "fyers": "NSE:JWL-EQ"},
    'ICICI Lombard General Insurance Company Ltd.': {"yahoo": "ICICIGI.NS", "fyers": "NSE:ICICIGI-EQ"},
    'Sarda Energy and Minerals Ltd.': {"yahoo": "SARDAEN.NS", "fyers": "NSE:SARDAEN-EQ"},
    'Dixon Technologies (India) Ltd.': {"yahoo": "DIXON.NS", "fyers": "NSE:DIXON-EQ"},
    'One 97 Communications Ltd.': {"yahoo": "PAYTM.NS", "fyers": "NSE:PAYTM-EQ"},
    'Gujarat State Petronet Ltd.': {"yahoo": "GSPL.NS", "fyers": "NSE:GSPL-EQ"},
    'LTIMindtree Ltd.': {"yahoo": "LTIM.NS", "fyers": "NSE:LTIM-EQ"},
    'Piramal Enterprises Ltd.': {"yahoo": "PEL.NS", "fyers": "NSE:PEL-EQ"},
    'Tata Motors Ltd.': {"yahoo": "TATAMOTORS.NS", "fyers": "NSE:TATAMOTORS-EQ"},
    'Swan Energy Ltd.': {"yahoo": "SWANENERGY.NS", "fyers": "NSE:SWANENERGY-EQ"},
    'Asahi India Glass Ltd.': {"yahoo": "ASAHIINDIA.NS", "fyers": "NSE:ASAHIINDIA-EQ"},
    'AstraZenca Pharma India Ltd.': {"yahoo": "ASTRAZEN.NS", "fyers": "NSE:ASTRAZEN-EQ"},
    'Tanla Platforms Ltd.': {"yahoo": "TANLA.NS", "fyers": "NSE:TANLA-EQ"},
    'IRB Infrastructure Developers Ltd.': {"yahoo": "IRB.NS", "fyers": "NSE:IRB-EQ"},
    '3M India Ltd.': {"yahoo": "3MINDIA.NS", "fyers": "NSE:3MINDIA-EQ"},
    'LIC Housing Finance Ltd.': {"yahoo": "LICHSGFIN.NS", "fyers": "NSE:LICHSGFIN-EQ"},
    'Bharat Electronics Ltd.': {"yahoo": "BEL.NS", "fyers": "NSE:BEL-EQ"},
    'General Insurance Corporation of India': {"yahoo": "GICRE.NS", "fyers": "NSE:GICRE-EQ"},
    'NHPC Ltd.': {"yahoo": "NHPC.NS", "fyers": "NSE:NHPC-EQ"},
    'Aadhar Housing Finance Ltd.': {"yahoo": "AADHARHFC.NS", "fyers": "NSE:AADHARHFC-EQ"},
    'PB Fintech Ltd.': {"yahoo": "POLICYBZR.NS", "fyers": "NSE:POLICYBZR-EQ"},
    'Bayer Cropscience Ltd.': {"yahoo": "BAYERCROP.NS", "fyers": "NSE:BAYERCROP-EQ"},
    'Indian Hotels Co. Ltd.': {"yahoo": "INDHOTEL.NS", "fyers": "NSE:INDHOTEL-EQ"},
    'GAIL (India) Ltd.': {"yahoo": "GAIL.NS", "fyers": "NSE:GAIL-EQ"},
    'Hindustan Aeronautics Ltd.': {"yahoo": "HAL.NS", "fyers": "NSE:HAL-EQ"},
    'TVS Motor Company Ltd.': {"yahoo": "TVSMOTOR.NS", "fyers": "NSE:TVSMOTOR-EQ"},
    'PTC Industries Ltd.': {"yahoo": "PTCIL.NS", "fyers": "NSE:PTCIL-EQ"},  # VERIFY
    'India Cements Ltd.': {"yahoo": "INDIACEM.NS", "fyers": "NSE:INDIACEM-EQ"},
    'Hindustan Petroleum Corporation Ltd.': {"yahoo": "HINDPETRO.NS", "fyers": "NSE:HINDPETRO-EQ"},
    'Gravita India Ltd.': {"yahoo": "GRAVITA.NS", "fyers": "NSE:GRAVITA-EQ"},
    'CreditAccess Grameen Ltd.': {"yahoo": "CREDITACC.NS", "fyers": "NSE:CREDITACC-EQ"},
    'Gujarat Pipavav Port Ltd.': {"yahoo": "GPPL.NS", "fyers": "NSE:GPPL-EQ"},
    'SJVN Ltd.': {"yahoo": "SJVN.NS", "fyers": "NSE:SJVN-EQ"},
    'Gillette India Ltd.': {"yahoo": "GILLETTE.NS", "fyers": "NSE:GILLETTE-EQ"},
    'Eris Lifesciences Ltd.': {"yahoo": "ERIS.NS", "fyers": "NSE:ERIS-EQ"},
    'Petronet LNG Ltd.': {"yahoo": "PETRONET.NS", "fyers": "NSE:PETRONET-EQ"},
    'Godrej Properties Ltd.': {"yahoo": "GODREJPROP.NS", "fyers": "NSE:GODREJPROP-EQ"},
    'UltraTech Cement Ltd.': {"yahoo": "ULTRACEMCO.NS", "fyers": "NSE:ULTRACEMCO-EQ"},
    'Tata Chemicals Ltd.': {"yahoo": "TATACHEM.NS", "fyers": "NSE:TATACHEM-EQ"},
    'Bank of India': {"yahoo": "BANKINDIA.NS", "fyers": "NSE:BANKINDIA-EQ"},
    'Castrol India Ltd.': {"yahoo": "CASTROLIND.NS", "fyers": "NSE:CASTROLIND-EQ"},
    'Bank of Baroda': {"yahoo": "BANKBARODA.NS", "fyers": "NSE:BANKBARODA-EQ"},
    'Bajaj Finance Ltd.': {"yahoo": "BAJFINANCE.NS", "fyers": "NSE:BAJFINANCE-EQ"},
    'Rashtriya Chemicals & Fertilizers Ltd.': {"yahoo": "RCF.NS", "fyers": "NSE:RCF-EQ"},
    'Eternal Ltd.': {"yahoo": "ETERNAL.NS", "fyers": "NSE:ETERNAL-EQ"},
    'Jubilant Ingrevia Ltd.': {"yahoo": "JUBLINGREA.NS", "fyers": "NSE:JUBLINGREA-EQ"},
    'Lodha Developers Ltd.': {"yahoo": "LODHA.NS", "fyers": "NSE:LODHA-EQ"},
    'SBI Life Insurance Company Ltd.': {"yahoo": "SBILIFE.NS", "fyers": "NSE:SBILIFE-EQ"},
    'City Union Bank Ltd.': {"yahoo": "CUB.NS", "fyers": "NSE:CUB-EQ"},
    'Aptus Value Housing Finance India Ltd.': {"yahoo": "APTUS.NS", "fyers": "NSE:APTUS-EQ"},
    'Cholamandalam Investment and Finance Company Ltd.': {"yahoo": "CHOLAFIN.NS", "fyers": "NSE:CHOLAFIN-EQ"},
    'UPL Ltd.': {"yahoo": "UPL.NS", "fyers": "NSE:UPL-EQ"},
    'JM Financial Ltd.': {"yahoo": "JMFINANCIL.NS", "fyers": "NSE:JMFINANCIL-EQ"},
    'Century Plyboards (India) Ltd.': {"yahoo": "CENTURYPLY.NS", "fyers": "NSE:CENTURYPLY-EQ"},
    'Coforge Ltd.': {"yahoo": "COFORGE.NS", "fyers": "NSE:COFORGE-EQ"},
    'Sundram Fasteners Ltd.': {"yahoo": "SUNDRMFAST.NS", "fyers": "NSE:SUNDRMFAST-EQ"},
    'IIFL Finance Ltd.': {"yahoo": "IIFL.NS", "fyers": "NSE:IIFL-EQ"},
    'Authum Investment & Infrastructure Ltd.': {"yahoo": "AIIL.NS", "fyers": "NSE:AIIL-EQ"},  # VERIFY
    'PCBL Chemical Ltd.': {"yahoo": "PCBL.NS", "fyers": "NSE:PCBL-EQ"},
    'Bajaj Holdings & Investment Ltd.': {"yahoo": "BAJAJHLDNG.NS", "fyers": "NSE:BAJAJHLDNG-EQ"},
    'Shree Cement Ltd.': {"yahoo": "SHREECEM.NS", "fyers": "NSE:SHREECEM-EQ"},
    'Vishal Mega Mart Ltd.': {"yahoo": "VMM.NS", "fyers": "NSE:VMM-EQ"},  # VERIFY
    'Kotak Mahindra Bank Ltd.': {"yahoo": "KOTAKBANK.NS", "fyers": "NSE:KOTAKBANK-EQ"},
    'Mahanagar Gas Ltd.': {"yahoo": "MGL.NS", "fyers": "NSE:MGL-EQ"},
    'UNO Minda Ltd.': {"yahoo": "UNOMINDA.NS", "fyers": "NSE:UNOMINDA-EQ"},
    'Sobha Ltd.': {"yahoo": "SOBHA.NS", "fyers": "NSE:SOBHA-EQ"},
    'Ashok Leyland Ltd.': {"yahoo": "ASHOKLEY.NS", "fyers": "NSE:ASHOKLEY-EQ"},
    'Home First Finance Company India Ltd.': {"yahoo": "HOMEFIRST.NS", "fyers": "NSE:HOMEFIRST-EQ"},
    'ICICI Bank Ltd.': {"yahoo": "ICICIBANK.NS", "fyers": "NSE:ICICIBANK-EQ"},
    'Aditya Birla Fashion and Retail Ltd.': {"yahoo": "ABFRL.NS", "fyers": "NSE:ABFRL-EQ"},
    'State Bank of India': {"yahoo": "SBIN.NS", "fyers": "NSE:SBIN-EQ"},
    'Firstsource Solutions Ltd.': {"yahoo": "FSL.NS", "fyers": "NSE:FSL-EQ"},
    'Campus Activewear Ltd.': {"yahoo": "CAMPUS.NS", "fyers": "NSE:CAMPUS-EQ"},
    'Techno Electric & Engineering Company Ltd.': {"yahoo": "TECHNOE.NS", "fyers": "NSE:TECHNOE-EQ"},
    'Cholamandalam Financial Holdings Ltd.': {"yahoo": "CHOLAHLDNG.NS", "fyers": "NSE:CHOLAHLDNG-EQ"},
    'Housing & Urban Development Corporation Ltd.': {"yahoo": "HUDCO.NS", "fyers": "NSE:HUDCO-EQ"},
    'Pfizer Ltd.': {"yahoo": "PFIZER.NS", "fyers": "NSE:PFIZER-EQ"},
    'APL Apollo Tubes Ltd.': {"yahoo": "APLAPOLLO.NS", "fyers": "NSE:APLAPOLLO-EQ"},
    'Colgate Palmolive (India) Ltd.': {"yahoo": "COLPAL.NS", "fyers": "NSE:COLPAL-EQ"},
    'IDFC First Bank Ltd.': {"yahoo": "IDFCFIRSTB.NS", "fyers": "NSE:IDFCFIRSTB-EQ"},
    'Indian Renewable Energy Development Agency Ltd.': {"yahoo": "IREDA.NS", "fyers": "NSE:IREDA-EQ"},
    'Muthoot Finance Ltd.': {"yahoo": "MUTHOOTFIN.NS", "fyers": "NSE:MUTHOOTFIN-EQ"},
    'Chalet Hotels Ltd.': {"yahoo": "CHALET.NS", "fyers": "NSE:CHALET-EQ"},
    'Bajaj Finserv Ltd.': {"yahoo": "BAJAJFINSV.NS", "fyers": "NSE:BAJAJFINSV-EQ"},
    'Mazagoan Dock Shipbuilders Ltd.': {"yahoo": "MAZDOCK.NS", "fyers": "NSE:MAZDOCK-EQ"},
    'Tech Mahindra Ltd.': {"yahoo": "TECHM.NS", "fyers": "NSE:TECHM-EQ"},
    'Hero MotoCorp Ltd.': {"yahoo": "HEROMOTOCO.NS", "fyers": "NSE:HEROMOTOCO-EQ"},
    'DLF Ltd.': {"yahoo": "DLF.NS", "fyers": "NSE:DLF-EQ"},
    'Railtel Corporation Of India Ltd.': {"yahoo": "RAILTEL.NS", "fyers": "NSE:RAILTEL-EQ"},
    'Affle 3i Ltd.': {"yahoo": "AFFLE.NS", "fyers": "NSE:AFFLE-EQ"},
    'Indian Energy Exchange Ltd.': {"yahoo": "IEX.NS", "fyers": "NSE:IEX-EQ"},
    'Jindal Stainless Ltd.': {"yahoo": "JSL.NS", "fyers": "NSE:JSL-EQ"},
    'Indian Oil Corporation Ltd.': {"yahoo": "IOC.NS", "fyers": "NSE:IOC-EQ"},
    'Prestige Estates Projects Ltd.': {"yahoo": "PRESTIGE.NS", "fyers": "NSE:PRESTIGE-EQ"},
    'SBFC Finance Ltd.': {"yahoo": "SBFC.NS", "fyers": "NSE:SBFC-EQ"},
    'Canara Bank': {"yahoo": "CANBK.NS", "fyers": "NSE:CANBK-EQ"},
    'RattanIndia Enterprises Ltd.': {"yahoo": "RTNINDIA.NS", "fyers": "NSE:RTNINDIA-EQ"},
    'Indian Overseas Bank': {"yahoo": "IOB.NS", "fyers": "NSE:IOB-EQ"},
    'Max Healthcare Institute Ltd.': {"yahoo": "MAXHEALTH.NS", "fyers": "NSE:MAXHEALTH-EQ"},
    'Bikaji Foods International Ltd.': {"yahoo": "BIKAJI.NS", "fyers": "NSE:BIKAJI-EQ"},
    'Persistent Systems Ltd.': {"yahoo": "PERSISTENT.NS", "fyers": "NSE:PERSISTENT-EQ"},
    'Motherson Sumi Wiring India Ltd.': {"yahoo": "MSUMI.NS", "fyers": "NSE:MSUMI-EQ"},
    'NCC Ltd.': {"yahoo": "NCC.NS", "fyers": "NSE:NCC-EQ"},
    'RHI MAGNESITA INDIA LTD.': {"yahoo": "RHIM.NS", "fyers": "NSE:RHIM-EQ"},
    'Afcons Infrastructure Ltd.': {"yahoo": "AFCONS.NS", "fyers": "NSE:AFCONS-EQ"},
    'Can Fin Homes Ltd.': {"yahoo": "CANFINHOME.NS", "fyers": "NSE:CANFINHOME-EQ"},
    'V-Guard Industries Ltd.': {"yahoo": "VGUARD.NS", "fyers": "NSE:VGUARD-EQ"},
    'InterGlobe Aviation Ltd.': {"yahoo": "INDIGO.NS", "fyers": "NSE:INDIGO-EQ"},
    'Redington Ltd.': {"yahoo": "REDINGTON.NS", "fyers": "NSE:REDINGTON-EQ"},
    'Balkrishna Industries Ltd.': {"yahoo": "BALKRISIND.NS", "fyers": "NSE:BALKRISIND-EQ"},
    'PVR INOX Ltd.': {"yahoo": "PVRINOX.NS", "fyers": "NSE:PVRINOX-EQ"},
    'Bharti Airtel Ltd.': {"yahoo": "BHARTIARTL.NS", "fyers": "NSE:BHARTIARTL-EQ"},
    'J.K. Cement Ltd.': {"yahoo": "JKCEMENT.NS", "fyers": "NSE:JKCEMENT-EQ"},
    'DCM Shriram Ltd.': {"yahoo": "DCMSHRIRAM.NS", "fyers": "NSE:DCMSHRIRAM-EQ"},
    'Alembic Pharmaceuticals Ltd.': {"yahoo": "APLLTD.NS", "fyers": "NSE:APLLTD-EQ"},
    'Gujarat Gas Ltd.': {"yahoo": "GUJGASLTD.NS", "fyers": "NSE:GUJGASLTD-EQ"},
    'UTI Asset Management Company Ltd.': {"yahoo": "UTIAMC.NS", "fyers": "NSE:UTIAMC-EQ"},
    'United Spirits Ltd.': {"yahoo": "UNITDSPR.NS", "fyers": "NSE:UNITDSPR-EQ"},
    'EIH Ltd.': {"yahoo": "EIHOTEL.NS", "fyers": "NSE:EIHOTEL-EQ"},
    'Maruti Suzuki India Ltd.': {"yahoo": "MARUTI.NS", "fyers": "NSE:MARUTI-EQ"},
    'Punjab National Bank': {"yahoo": "PNB.NS", "fyers": "NSE:PNB-EQ"},
    'Reliance Industries Ltd.': {"yahoo": "RELIANCE.NS", "fyers": "NSE:RELIANCE-EQ"},
    'Tata Teleservices (Maharashtra) Ltd.': {"yahoo": "TTML.NS", "fyers": "NSE:TTML-EQ"},
    'REC Ltd.': {"yahoo": "RECLTD.NS", "fyers": "NSE:RECLTD-EQ"},
    'Hyundai Motor India Ltd.': {"yahoo": "HYUNDAI.NS", "fyers": "NSE:HYUNDAI-EQ"},
    'Bharat Petroleum Corporation Ltd.': {"yahoo": "BPCL.NS", "fyers": "NSE:BPCL-EQ"},
    'KNR Constructions Ltd.': {"yahoo": "KNRCON.NS", "fyers": "NSE:KNRCON-EQ"},
    'Blue Star Ltd.': {"yahoo": "BLUESTARCO.NS", "fyers": "NSE:BLUESTARCO-EQ"},
    'Bharti Hexacom Ltd.': {"yahoo": "BHARTIHEXA.NS", "fyers": "NSE:BHARTIHEXA-EQ"},
    'JK Tyre & Industries Ltd.': {"yahoo": "JKTYRE.NS", "fyers": "NSE:JKTYRE-EQ"},
    'Aavas Financiers Ltd.': {"yahoo": "AAVAS.NS", "fyers": "NSE:AAVAS-EQ"},
    'Mahindra & Mahindra Financial Services Ltd.': {"yahoo": "M&MFIN.NS", "fyers": "NSE:M&MFIN-EQ"},
    'Indraprastha Gas Ltd.': {"yahoo": "IGL.NS", "fyers": "NSE:IGL-EQ"},
    'Bajaj Housing Finance Ltd.': {"yahoo": "BAJAJHFL.NS", "fyers": "NSE:BAJAJHFL-EQ"},
    'Trident Ltd.': {"yahoo": "TRIDENT.NS", "fyers": "NSE:TRIDENT-EQ"},
    'Mahindra & Mahindra Ltd.': {"yahoo": "M&M.NS", "fyers": "NSE:M&M-EQ"},
    'SKF India Ltd.': {"yahoo": "SKFINDIA.NS", "fyers": "NSE:SKFINDIA-EQ"},
    'Mangalore Refinery & Petrochemicals Ltd.': {"yahoo": "MRPL.NS", "fyers": "NSE:MRPL-EQ"},
    'Container Corporation of India Ltd.': {"yahoo": "CONCOR.NS", "fyers": "NSE:CONCOR-EQ"},
    'DOMS Industries Ltd.': {"yahoo": "DOMS.NS", "fyers": "NSE:DOMS-EQ"},
    'Poonawalla Fincorp Ltd.': {"yahoo": "POONAWALLA.NS", "fyers": "NSE:POONAWALLA-EQ"},
    'Latent View Analytics Ltd.': {"yahoo": "LATENTVIEW.NS", "fyers": "NSE:LATENTVIEW-EQ"},
    'Sagility India Ltd.': {"yahoo": "SAGILITY.NS", "fyers": "NSE:SAGILITY-EQ"},
    'Ambuja Cements Ltd.': {"yahoo": "AMBUJACEM.NS", "fyers": "NSE:AMBUJACEM-EQ"},
    'MRF Ltd.': {"yahoo": "MRF.NS", "fyers": "NSE:MRF-EQ"},
    'PNC Infratech Ltd.': {"yahoo": "PNCINFRA.NS", "fyers": "NSE:PNCINFRA-EQ"},
    'Clean Science and Technology Ltd.': {"yahoo": "CLEAN.NS", "fyers": "NSE:CLEAN-EQ"},
    'Patanjali Foods Ltd.': {"yahoo": "PATANJALI.NS", "fyers": "NSE:PATANJALI-EQ"},
    'Go Digit General Insurance Ltd.': {"yahoo": "GODIGIT.NS", "fyers": "NSE:GODIGIT-EQ"},
    'Dabur India Ltd.': {"yahoo": "DABUR.NS", "fyers": "NSE:DABUR-EQ"},
    'Voltas Ltd.': {"yahoo": "VOLTAS.NS", "fyers": "NSE:VOLTAS-EQ"},
    'Cyient Ltd.': {"yahoo": "CYIENT.NS", "fyers": "NSE:CYIENT-EQ"},
    'Britannia Industries Ltd.': {"yahoo": "BRITANNIA.NS", "fyers": "NSE:BRITANNIA-EQ"},
    'Hindustan Unilever Ltd.': {"yahoo": "HINDUNILVR.NS", "fyers": "NSE:HINDUNILVR-EQ"},
    'Jio Financial Services Ltd.': {"yahoo": "JIOFIN.NS", "fyers": "NSE:JIOFIN-EQ"},
    'Glaxosmithkline Pharmaceuticals Ltd.': {"yahoo": "GLAXO.NS", "fyers": "NSE:GLAXO-EQ"},
    'Indiamart Intermesh Ltd.': {"yahoo": "INDIAMART.NS", "fyers": "NSE:INDIAMART-EQ"},
    'Havells India Ltd.': {"yahoo": "HAVELLS.NS", "fyers": "NSE:HAVELLS-EQ"},
    'Lemon Tree Hotels Ltd.': {"yahoo": "LEMONTREE.NS", "fyers": "NSE:LEMONTREE-EQ"},
    'Devyani International Ltd.': {"yahoo": "DEVYANI.NS", "fyers": "NSE:DEVYANI-EQ"},
    'Cohance Lifesciences Ltd.': {"yahoo": "COHANCE.NS", "fyers": "NSE:COHANCE-EQ"},  # VERIFY
    'HDFC Life Insurance Company Ltd.': {"yahoo": "HDFCLIFE.NS", "fyers": "NSE:HDFCLIFE-EQ"},
    'Central Depository Services (India) Ltd.': {"yahoo": "CDSL.NS", "fyers": "NSE:CDSL-EQ"},
    'Sterling and Wilson Renewable Energy Ltd.': {"yahoo": "SWSOLAR.NS", "fyers": "NSE:SWSOLAR-EQ"},
    'BLS International Services Ltd.': {"yahoo": "BLS.NS", "fyers": "NSE:BLS-EQ"},
    'Wipro Ltd.': {"yahoo": "WIPRO.NS", "fyers": "NSE:WIPRO-EQ"},
    'UCO Bank': {"yahoo": "UCOBANK.NS", "fyers": "NSE:UCOBANK-EQ"},
    'BASF India Ltd.': {"yahoo": "BASF.NS", "fyers": "NSE:BASF-EQ"},
    'RITES Ltd.': {"yahoo": "RITES.NS", "fyers": "NSE:RITES-EQ"},
    'Bombay Burmah Trading Corporation Ltd.': {"yahoo": "BBTC.NS", "fyers": "NSE:BBTC-EQ"},
    'Happiest Minds Technologies Ltd.': {"yahoo": "HAPPSTMNDS.NS", "fyers": "NSE:HAPPSTMNDS-EQ"},
    'Godrej Consumer Products Ltd.': {"yahoo": "GODREJCP.NS", "fyers": "NSE:GODREJCP-EQ"},
    'MphasiS Ltd.': {"yahoo": "MPHASIS.NS", "fyers": "NSE:MPHASIS-EQ"},
    'L&T Technology Services Ltd.': {"yahoo": "LTTS.NS", "fyers": "NSE:LTTS-EQ"},
    'Tata Elxsi Ltd.': {"yahoo": "TATAELXSI.NS", "fyers": "NSE:TATAELXSI-EQ"},
    'Sonata Software Ltd.': {"yahoo": "SONATSOFTW.NS", "fyers": "NSE:SONATSOFTW-EQ"},
    'Westlife Foodworld Ltd.': {"yahoo": "WESTLIFE.NS", "fyers": "NSE:WESTLIFE-EQ"},
    'Cochin Shipyard Ltd.': {"yahoo": "COCHINSHIP.NS", "fyers": "NSE:COCHINSHIP-EQ"},
    'AWL Agri Business Ltd.': {"yahoo": "AWL.NS", "fyers": "NSE:AWL-EQ"},
    'Sundaram Finance Ltd.': {"yahoo": "SUNDARMFIN.NS", "fyers": "NSE:SUNDARMFIN-EQ"},
    'TBO Tek Ltd.': {"yahoo": "TBOTEK.NS", "fyers": "NSE:TBOTEK-EQ"},
    'CRISIL Ltd.': {"yahoo": "CRISIL.NS", "fyers": "NSE:CRISIL-EQ"},
    'Sun TV Network Ltd.': {"yahoo": "SUNTV.NS", "fyers": "NSE:SUNTV-EQ"},
    'Dalmia Bharat Ltd.': {"yahoo": "DALBHARAT.NS", "fyers": "NSE:DALBHARAT-EQ"},
    'ACC Ltd.': {"yahoo": "ACC.NS", "fyers": "NSE:ACC-EQ"},
    'ICICI Prudential Life Insurance Company Ltd.': {"yahoo": "ICICIPRULI.NS", "fyers": "NSE:ICICIPRULI-EQ"},
    'Shree Renuka Sugars Ltd.': {"yahoo": "RENUKA.NS", "fyers": "NSE:RENUKA-EQ"},
    'Signatureglobal (India) Ltd.': {"yahoo": "SIGNATURE.NS", "fyers": "NSE:SIGNATURE-EQ"},
    'Reliance Power Ltd.': {"yahoo": "RPOWER.NS", "fyers": "NSE:RPOWER-EQ"},
    'Ceat Ltd.': {"yahoo": "CEATLTD.NS", "fyers": "NSE:CEATLTD-EQ"},
    'Indian Railway Finance Corporation Ltd.': {"yahoo": "IRFC.NS", "fyers": "NSE:IRFC-EQ"},
    'Whirlpool of India Ltd.': {"yahoo": "WHIRLPOOL.NS", "fyers": "NSE:WHIRLPOOL-EQ"},
    'IRCON International Ltd.': {"yahoo": "IRCON.NS", "fyers": "NSE:IRCON-EQ"},
    'Syngene International Ltd.': {"yahoo": "SYNGENE.NS", "fyers": "NSE:SYNGENE-EQ"},
    'The Ramco Cements Ltd.': {"yahoo": "RAMCOCEM.NS", "fyers": "NSE:RAMCOCEM-EQ"},
    'Mastek Ltd.': {"yahoo": "MASTEK.NS", "fyers": "NSE:MASTEK-EQ"},
    'Alok Industries Ltd.': {"yahoo": "ALOKINDS.NS", "fyers": "NSE:ALOKINDS-EQ"},
    'PI Industries Ltd.': {"yahoo": "PIIND.NS", "fyers": "NSE:PIIND-EQ"},
    'HDFC Bank Ltd.': {"yahoo": "HDFCBANK.NS", "fyers": "NSE:HDFCBANK-EQ"},
    'PG Electroplast Ltd.': {"yahoo": "PGEL.NS", "fyers": "NSE:PGEL-EQ"},
    'United Breweries Ltd.': {"yahoo": "UBL.NS", "fyers": "NSE:UBL-EQ"},
    'Concord Biotech Ltd.': {"yahoo": "CONCORDBIO.NS", "fyers": "NSE:CONCORDBIO-EQ"},
    'Blue Dart Express Ltd.': {"yahoo": "BLUEDART.NS", "fyers": "NSE:BLUEDART-EQ"},
    'IDBI Bank Ltd.': {"yahoo": "IDBI.NS", "fyers": "NSE:IDBI-EQ"},
    'Indian Railway Catering And Tourism Corporation Ltd.': {"yahoo": "IRCTC.NS", "fyers": "NSE:IRCTC-EQ"},
    'Kalyan Jewellers India Ltd.': {"yahoo": "KALYANKJIL.NS", "fyers": "NSE:KALYANKJIL-EQ"},
    'Brainbees Solutions Ltd.': {"yahoo": "FIRSTCRY.NS", "fyers": "NSE:FIRSTCRY-EQ"},
    'Justdial Ltd.': {"yahoo": "JUSTDIAL.NS", "fyers": "NSE:JUSTDIAL-EQ"},
    'eClerx Services Ltd.': {"yahoo": "ECLERX.NS", "fyers": "NSE:ECLERX-EQ"},
    'Infosys Ltd.': {"yahoo": "INFY.NS", "fyers": "NSE:INFY-EQ"},
    'Apollo Tyres Ltd.': {"yahoo": "APOLLOTYRE.NS", "fyers": "NSE:APOLLOTYRE-EQ"},
    'Info Edge (India) Ltd.': {"yahoo": "NAUKRI.NS", "fyers": "NSE:NAUKRI-EQ"},
    'Central Bank of India': {"yahoo": "CENTRALBK.NS", "fyers": "NSE:CENTRALBK-EQ"},
    'E.I.D. Parry (India) Ltd.': {"yahoo": "EIDPARRY.NS", "fyers": "NSE:EIDPARRY-EQ"},
    'Sapphire Foods India Ltd.': {"yahoo": "SAPPHIRE.NS", "fyers": "NSE:SAPPHIRE-EQ"},
    'ITC Ltd.': {"yahoo": "ITC.NS", "fyers": "NSE:ITC-EQ"},
    'Network18 Media & Investments Ltd.': {"yahoo": "NETWORK18.NS", "fyers": "NSE:NETWORK18-EQ"},
    'Inox Wind Ltd.': {"yahoo": "INOXWIND.NS", "fyers": "NSE:INOXWIND-EQ"},
    'Coromandel International Ltd.': {"yahoo": "COROMANDEL.NS", "fyers": "NSE:COROMANDEL-EQ"},
    'Route Mobile Ltd.': {"yahoo": "ROUTE.NS", "fyers": "NSE:ROUTE-EQ"},
    'Kfin Technologies Ltd.': {"yahoo": "KFINTECH.NS", "fyers": "NSE:KFINTECH-EQ"},
    'Swiggy Ltd.': {"yahoo": "SWIGGY.NS", "fyers": "NSE:SWIGGY-EQ"},
    'SBI Cards and Payment Services Ltd.': {"yahoo": "SBICARD.NS", "fyers": "NSE:SBICARD-EQ"},
    'Jubilant Foodworks Ltd.': {"yahoo": "JUBLFOOD.NS", "fyers": "NSE:JUBLFOOD-EQ"},
    'JSW Holdings Ltd.': {"yahoo": "JSWHL.NS", "fyers": "NSE:JSWHL-EQ"},
    'Escorts Kubota Ltd.': {"yahoo": "ESCORTS.NS", "fyers": "NSE:ESCORTS-EQ"},
    'Intellect Design Arena Ltd.': {"yahoo": "INTELLECT.NS", "fyers": "NSE:INTELLECT-EQ"},
    'Vedant Fashions Ltd.': {"yahoo": "MANYAVAR.NS", "fyers": "NSE:MANYAVAR-EQ"},
    'Birlasoft Ltd.': {"yahoo": "BSOFT.NS", "fyers": "NSE:BSOFT-EQ"},
    'Five-Star Business Finance Ltd.': {"yahoo": "FIVESTAR.NS", "fyers": "NSE:FIVESTAR-EQ"},
    'Bharat Dynamics Ltd.': {"yahoo": "BDL.NS", "fyers": "NSE:BDL-EQ"},
    'KPIT Technologies Ltd.': {"yahoo": "KPITTECH.NS", "fyers": "NSE:KPITTECH-EQ"},
    'HCL Technologies Ltd.': {"yahoo": "HCLTECH.NS", "fyers": "NSE:HCLTECH-EQ"},
    'Poly Medicure Ltd.': {"yahoo": "POLYMED.NS", "fyers": "NSE:POLYMED-EQ"},
    'Aditya Birla Real Estate Ltd.': {"yahoo": "ABREL.NS", "fyers": "NSE:ABREL-EQ"},
    'Emami Ltd.': {"yahoo": "EMAMILTD.NS", "fyers": "NSE:EMAMILTD-EQ"},
    'Bata India Ltd.': {"yahoo": "BATAINDIA.NS", "fyers": "NSE:BATAINDIA-EQ"},
    'Brigade Enterprises Ltd.': {"yahoo": "BRIGADE.NS", "fyers": "NSE:BRIGADE-EQ"},
    'Tata Consultancy Services Ltd.': {"yahoo": "TCS.NS", "fyers": "NSE:TCS-EQ"},
    'Zensar Technolgies Ltd.': {"yahoo": "ZENSARTECH.NS", "fyers": "NSE:ZENSARTECH-EQ"},
    'Kec International Ltd.': {"yahoo": "KEC.NS", "fyers": "NSE:KEC-EQ"},
    'Jyoti CNC Automation Ltd.': {"yahoo": "JYOTICNC.NS", "fyers": "NSE:JYOTICNC-EQ"},
    'Kaynes Technology India Ltd.': {"yahoo": "KAYNES.NS", "fyers": "NSE:KAYNES-EQ"},
    'Raymond Lifestyle Ltd.': {"yahoo": "RAYMONDLSL.NS", "fyers": "NSE:RAYMONDLSL-EQ"},
    'Rail Vikas Nigam Ltd.': {"yahoo": "RVNL.NS", "fyers": "NSE:RVNL-EQ"},
    'Jyothy Labs Ltd.': {"yahoo": "JYOTHYLAB.NS", "fyers": "NSE:JYOTHYLAB-EQ"},
    'Newgen Software Technologies Ltd.': {"yahoo": "NEWGEN.NS", "fyers": "NSE:NEWGEN-EQ"},
    'C.E. Info Systems Ltd.': {"yahoo": "MAPMYINDIA.NS", "fyers": "NSE:MAPMYINDIA-EQ"},
    'Vedanta Ltd.': {"yahoo": "VEDL.NS", "fyers": "NSE:VEDL-EQ"},
    'Life Insurance Corporation of India': {"yahoo": "LICI.NS", "fyers": "NSE:LICI-EQ"},
}
